name: nvidia-assemble
adopt-info: nvidia-assemble
grade: stable
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  nvidia-assemble:
    command: nvidia-assemble
    daemon: oneshot
    plugs:
      - modprobe-nvidia

plugs:
  modprobe-nvidia:
    interface: kernel-module-load
    modules:
      - name: nvidia-drm
        load: dynamic
        options: modeset=1
      - name: nvidia-uvm
        load: dynamic

parts:

  nvidia-assemble:
    plugin: dump
    source: .
    build-packages:
      - git
    override-build: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    stage-packages:
      - binutils
    stage:
      - nvidia-assemble
      - usr/lib/*/lib*
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
