name: nvidia-assemble
adopt-info: version
grade: stable
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  nvidia-assemble:
    command: commands/nvidia-assemble
    daemon: oneshot
    plugs:
      - kernel-module-control

parts:

  version:
    plugin: nil
    source: .
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    override-stage: |
      true

  nvidia-assemble:
    plugin: dump
    source: ./nvidia-assemble/

  deps:
    plugin: nil
    build-packages:
      - dpkg-dev
    stage-packages:
      - binutils
    stage:
      - usr/lib/*/lib*
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
