name: nvidia-assemble
adopt-info: nvidia-assemble
grade: stable
license: GPL-3.0
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core24
assumes:
  - snapd2.59

platforms:
  amd64:
  arm64:

apps:
  nvidia-assemble:
    command: nvidia-assemble
    daemon: oneshot

plugs:
  nvidia-drivers-support:
  modprobe-nvidia:
    interface: kernel-module-load
    modules:
      - name: nvidia-drm
        load: dynamic
        options: modeset=1
      - name: nvidia-uvm
        load: dynamic
  kernel-module-access:
    interface: system-files
    read:
      - /snap/pc-kernel
  proc-devices-access:
    interface: system-files
    read:
      - /proc/devices

parts:

  nvidia-assemble:
    plugin: dump
    source: .
    build-packages:
      - git
    override-build: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    stage-packages:
      - binutils
    stage:
      - nvidia-assemble
      - usr/lib/*/lib*
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
