name: nvidia-assemble
adopt-info: set_version
grade: stable
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  nvidia-assemble:
    command: commands/nvidia-assemble
    daemon: oneshot
    plugs:
      - modprobe-nvidia

plugs:
  modprobe-nvidia:
    interface: kernel-module-load
    modules:
      - name: nvidia-drm
        load: dynamic
        options: modeset=1
      - name: nvidia-uvm
        load: dynamic

parts:

  set_version:
    plugin: nil
    source: .
    build-packages:
      - git
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags)"
    override-stage: |
      true

  nvidia-assemble:
    plugin: dump
    source: ./nvidia-assemble/

  deps:
    plugin: nil
    build-packages:
      - dpkg-dev
    stage-packages:
      - binutils
    stage:
      - usr/lib/*/lib*
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
