name: nvidia-assemble
adopt-info: version
grade: stable
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core20

plugs:
  udev-rules:
    interface: system-files
    write:
      - /etc/udev/rules.d

  modprobe:
    interface: system-files
    write:
      - /etc/modprobe.d

apps:
  nvidia-assemble:
    command: commands/nvidia-assemble
    plugs:
      - udev-rules
      - modprobe
  ub-device-create:
    command: sbin/ub-device-create

parts:

  version:
    plugin: nil
    source: .
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    override-stage: |
      true

  nvidia-assemble:
    plugin: dump
    source: ./nvidia-assemble/

  deps:
    plugin: nil
    stage-packages:
      - binutils
      - nvidia-kernel-common-470-server
    stage:
      - sbin/ub-device-create
      - usr/lib/*/lib*
      - lib/modprobe.d/
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
